version: "3.7"
services:
  db:
    image: postgres:13
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: ahyoshin
      POSTGRES_USER: user  #temporary
      POSTGRES_PASSWORD: user!123 #temporary
